name: quds_formula_parser
description: A Fast formula parser and evaulator, written by pure dart.
version: 0.0.1
repository: https://github.com/MohammedAsaadAsaad/quds_formula_parser

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
