name: quds_formula_parser
description: Dart package designed for parsing and evaluating mathematical, logical, and textual formulas. It enables developers to input complex expressions.
version: 0.0.4
repository: https://github.com/MohammedAsaadAsaad/quds_formula_parser

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

screenshots:
 - description: 'Plotting a formula graph as a result of using the package.'
   path: example/screenshots/flutter_example_usage.png
 - description: 'Parsing and evaluating a formula.'
   path: example/screenshots/dart_example.png
